version: "3.9"

services:
  protheus-appserver:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: protheus-appserver
    working_dir: /totvs/protheus/bin
    command: >
      sh -c "envsubst < appserver_base.ini > appserver.ini && ./appsrvlinux"
    volumes:
      - ./bin:/totvs/protheus/bin
      - ./appserver.ini:/totvs/protheus/bin/appserver_base.ini
      - ./protheus_data:/protheus_data
    devices:
      - "/dev/mem:/dev/mem"
    cap_add:
      - SYS_RAWIO
    ulimits:
      core:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
      stack:
        soft: 1048576
        hard: 1048576
    restart: unless-stopped
    networks:
        - protheus
    restart: always

networks:
    protheus:
